site_name: VSR for VATSIM
repo_url: https://github.com/daveblackuk/VSR

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/AGnazfDwYZ

theme:
  name: material
  logo: assets/engineer_edited.ico
  favicon: assets/engineer_edited.ico
  features:
    - search.suggest
    - navigation.tabs
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css
plugins:
  - search
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg